let H=10,candles=[],features=[],live={},preview=null;
const $=id=>document.getElementById(id);
function log(s){$('log').textContent+='\n'+s;$('log').scrollTop=$('log').scrollHeight}
function setStatus(s,on=false){$('status').textContent=s;$('statusPill').className='pill'+(on?' live':'')}
function money(n){return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n):'--'}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function qtile(a,q){if(!a.length)return 0;a=[...a].sort((x,y)=>x-y);let p=(a.length-1)*q,b=Math.floor(p),r=p-b;return a[b+1]!==undefined?a[b]+r*(a[b+1]-a[b]):a[b]}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function logit(p){p=clamp(p,.02,.98);return Math.log(p/(1-p))}
function sigmoid(x){return 1/(1+Math.exp(-x))}
async function getJSON(url,ms=10000){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:ac.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadCoinbaseHistory(){log('Loading 10 days of Coinbase 5-minute candles…');const now=Math.floor(Date.now()/1000),floor=now-10*86400,slice=299*300,all=[];for(let end=now;end>floor;end-=slice){const start=Math.max(floor,end-slice);const u=`https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=300&start=${new Date(start*1000).toISOString()}&end=${new Date(end*1000).toISOString()}`;const rows=await getJSON(u,12000);if(!Array.isArray(rows))throw new Error('Coinbase candles format');rows.forEach(x=>{if(Array.isArray(x)&&x.length>=6)all.push({t:+x[0],l:+x[1],h:+x[2],o:+x[3],c:+x[4],v:+x[5]})})}const m=new Map();all.forEach(x=>m.set(x.t,x));const out=[...m.values()].sort((a,b)=>a.t-b.t);if(out.length<1000)throw new Error('Only '+out.length+' historical candles');return out}
async function cbTicker(){const j=await getJSON('https://api.exchange.coinbase.com/products/BTC-USD/ticker',7000);return{price:+j.price,bid:+j.bid,ask:+j.ask}}
async function cbBook(){const j=await getJSON('https://api.exchange.coinbase.com/products/BTC-USD/book?level=2',9000),b=j.bids||[],a=j.asks||[];if(!b.length||!a.length)throw new Error('empty book');const mid=(+b[0][0]+ +a[0][0])/2,band=.0025;let bn=0,an=0;b.forEach(x=>{let p=+x[0],s=+x[1];if((mid-p)/mid<=band)bn+=p*s});a.forEach(x=>{let p=+x[0],s=+x[1];if((p-mid)/mid<=band)an+=p*s});return{score:(bn-an)/Math.max(1,bn+an)}}
async function cbTradeFlow(){const rows=await getJSON('https://api.exchange.coinbase.com/products/BTC-USD/trades',9000);if(!Array.isArray(rows))throw new Error('trade format');let buy=0,sell=0;rows.slice(0,100).forEach(x=>{let n=(+x.price)*(+x.size);if(x.side==='sell')buy+=n;else if(x.side==='buy')sell+=n});return{score:(buy-sell)/Math.max(1,buy+sell)}}
function krakenKey(obj){return Object.keys(obj||{}).find(k=>k!=='last')}
async function kTicker(){const j=await getJSON('https://api.kraken.com/0/public/Ticker?pair=XBTUSD',7000);if(j.error?.length)throw new Error(j.error.join(','));const k=krakenKey(j.result),x=j.result[k];return{price:+x.c[0],bid:+x.b[0],ask:+x.a[0]}}
async function kBook(){const j=await getJSON('https://api.kraken.com/0/public/Depth?pair=XBTUSD&count=100',9000);if(j.error?.length)throw new Error(j.error.join(','));const k=krakenKey(j.result),x=j.result[k],b=x.bids||[],a=x.asks||[];if(!b.length||!a.length)throw new Error('empty Kraken book');const mid=(+b[0][0]+ +a[0][0])/2,band=.0025;let bn=0,an=0;b.forEach(y=>{let p=+y[0],s=+y[1];if((mid-p)/mid<=band)bn+=p*s});a.forEach(y=>{let p=+y[0],s=+y[1];if((p-mid)/mid<=band)an+=p*s});return{score:(bn-an)/Math.max(1,bn+an)}}
async function kTradeFlow(){const j=await getJSON('https://api.kraken.com/0/public/Trades?pair=XBTUSD',9000);if(j.error?.length)throw new Error(j.error.join(','));const k=krakenKey(j.result),rows=j.result[k]||[];let buy=0,sell=0;rows.slice(-250).forEach(x=>{let n=(+x[0])*(+x[1]);if(x[3]==='b')buy+=n;else if(x[3]==='s')sell+=n});return{score:(buy-sell)/Math.max(1,buy+sell)}}
function rsi(i,p=14){if(i<p)return 50;let g=0,l=0;for(let x=i-p+1;x<=i;x++){const d=candles[x].c-candles[x-1].c;if(d>=0)g+=d;else l-=d}if(!l)return 100;const rs=g/l;return 100-100/(1+rs)}
function emaSeries(p){const out=[],k=2/(p+1);let e=candles[0].c;for(let i=0;i<candles.length;i++){if(i)e=candles[i].c*k+e*(1-k);out[i]=e}return out}
function buildFeatures(){const e9=emaSeries(9),e21=emaSeries(21);features=new Array(candles.length).fill(null);for(let i=25;i<candles.length;i++){const c=candles[i].c,ret=n=>c/candles[i-n].c-1,recent=candles.slice(i-19,i+1),lo=Math.min(...recent.map(x=>x.l)),hi=Math.max(...recent.map(x=>x.h)),vr=candles[i].v/Math.max(1e-9,avg(recent.map(x=>x.v)));features[i]=[ret(1)/.004,ret(3)/.008,ret(6)/.012,ret(12)/.02,(rsi(i)-50)/25,((e9[i]-e21[i])/c)/.006,((c-lo)/Math.max(1e-9,hi-lo)-.5)*2,Math.log(Math.max(.05,vr))/1.5]}}
function dist(a,b){let s=0;for(let z=0;z<a.length;z++){let d=a[z]-b[z];s+=d*d}return Math.sqrt(s/a.length)}
function histPredict(index,hBars,k=55,window=1800){const tgt=features[index];if(!tgt)return null;let pts=[],start=Math.max(25,index-window);for(let j=start;j+hBars<=index-1;j++){if(!features[j])continue;const rr=candles[j+hBars].c/candles[j].c-1;pts.push({d:dist(tgt,features[j]),ret:rr,up:rr>0})}if(pts.length<300)return null;pts.sort((a,b)=>a.d-b.d);const near=pts.slice(0,Math.min(k,pts.length));let wt=0,wu=0;near.forEach(x=>{const w=1/Math.pow(x.d+.15,2);wt+=w;if(x.up)wu+=w});const rr=near.map(x=>x.ret);return{p:wu/wt,med:qtile(rr,.5),q20:qtile(rr,.2),q80:qtile(rr,.8),n:near.length}}
function backtest(hBars){const final=candles.length-hBars-1,start=Math.max(500,final-260);let right=0,total=0,ups=0;for(let i=start;i<=final;i++){const p=histPredict(i,hBars,45,1500);if(!p)continue;const actual=candles[i+hBars].c>candles[i].c;if((p.p>=.5)===actual)right++;if(actual)ups++;total++}const acc=total?right/total:0,ur=total?ups/total:.5,base=Math.max(ur,1-ur);return{acc,base,edge:acc-base,total}}
function vote(id,score,avail=true){const e=$(id);if(!avail){e.textContent='OFFLINE';e.className='vote bad';return}if(score>.10){e.textContent='BULLISH';e.className='vote ok'}else if(score<-.10){e.textContent='BEARISH';e.className='vote bad'}else{e.textContent='NEUTRAL';e.className='vote neutral'}}