// Editorial queue. Only scheduled, complete entries publish on or after publishOn.
// These are original business-process guides, not case studies or customer results.
export const guides = [
 {slug:'ai-receptionist-cost',title:'What does an AI receptionist actually cost?',category:'AI front desk',service:'ai-front-desk',publishOn:'2026-09-13',status:'scheduled',description:'Separate setup, monthly service, usage, and integrations before comparing AI receptionist proposals.',takeaway:'Compare the total agreed scope: setup + monthly service + usage + connections + support.',sections:[
 ['Start with the conversation you need','An AI receptionist price only makes sense next to the job it needs to do. Answering approved questions and collecting callback details is a different scope from booking appointments, checking live records, or routing calls across several locations. Write down the main caller needs before comparing proposals. Decide which calls should reach a person and what information the team needs when that happens.'],
 ['Separate setup from monthly service','Dream Protocol’s published front-desk starting price is $399 per month, with setup from $995 for one business/location. Setup covers business knowledge and call-flow configuration within the agreed scope. Monthly service and one-time setup should appear separately in a proposal so you can understand both the first invoice and ongoing cost.'],
 ['Make usage explicit','Ask what usage allowance is included, how usage is measured, and what happens when the allowance is exceeded. Request the overage terms before launch. A business with a few brief inquiries has a different call pattern from one with frequent, detailed conversations. Use your existing call records where available rather than assuming the advertised monthly figure covers every volume.'],
 ['Check connections and support','Calendar booking, CRM updates, multiple locations, or custom routing can change the project. Compatibility depends on available APIs and account access. Software licenses and third-party usage may add costs. Dream Protocol’s managed AI support starts separately at $750 per month; do not assume that plan is included in the $399 front-desk starting price.'],
 ['Compare the first year using the same assumptions','Use this worksheet: setup + (12 × monthly service) + estimated usage charges + required software + separately scoped support. Leave unknown figures visible until the provider supplies them. Compare what the caller experiences, how exceptions are handled, and what your team receives—not only the monthly headline.']
 ],checklist:['One location or several?','Questions only, callback intake, or confirmed booking?','Included usage and overage terms?','Setup and integration charges?','Who handles updates and exceptions?']},
 {slug:'choose-first-automation',title:'How to choose your first business automation',category:'Workflow automation',service:'workflow-automation',publishOn:'2026-09-13',status:'scheduled',description:'Pick a repeatable process with a clear owner, reliable inputs, and a result your team can check.',takeaway:'The best first project is a small, well-understood process with a visible handoff.',sections:[
 ['Look for repetition with a clear finish','List the tasks your team repeats during an ordinary week. A useful candidate has a recognizable trigger and an observable outcome: a website inquiry becomes an assigned task, for example. Avoid starting with “automate the whole office.” That hides the decisions, dependencies, and exceptions you need to understand.'],
 ['Map one real example','Take a recent request and write down every step from arrival to completion. Record the tools used, information copied, person responsible, and points where the work waits. Ask the people doing the task to check the map. If different staff describe different processes, agree on the intended process before building around it.'],
 ['Check whether the inputs are dependable','A workflow cannot route an inquiry by service type if the service field is usually missing. Identify the required fields, where they come from, and what should happen when they are incomplete. Simple form improvements or a clearer checklist may solve part of the problem before any automation is needed.'],
 ['Keep an owner for exceptions','Choose who receives an alert when a connection fails or a request does not fit the rules. Define how staff can complete the work manually. For a first project, favor a task where someone can easily inspect the result and correct a mistake before it affects a customer.'],
 ['Measure the same thing before and after','Record a practical baseline: time spent copying a request, number of incomplete handoffs, or time until a task is assigned. After launch, review comparable examples. Treat any projected savings as a hypothesis until you have measured the actual result. Dream Protocol’s starting workflow scope covers one workflow across up to two existing tools, with testing and handoff.']
 ],checklist:['Clear trigger and completion point','Required fields available','One accountable owner','Manual path when the connection fails','Baseline that can be measured again']},
 {slug:'first-ai-workshop',title:'What to bring to your first team AI workshop',category:'AI training',service:'ai-training',publishOn:'2026-09-21',status:'scheduled',description:'Prepare approved examples, a realistic task, and clear review criteria so your team can practice on useful work.',takeaway:'Bring a real task, approved sample information, and a clear definition of a good result.',sections:[
 ['Choose a task the team recognizes','A routine customer reply, a meeting summary, or an internal instruction is a useful starting point. Choose a task that happens often enough for staff to practice again after the workshop. Bring the current process as well as the desired output. A shared example makes it easier to compare approaches and understand where the AI helped.'],
 ['Prepare safe sample information','Use approved, non-sensitive examples or remove identifying details before the session. Check which AI tools your business allows and what information staff may enter. The exercise should help people learn a repeatable method without requiring live customer records or credentials.'],
 ['Decide what good looks like','Write down what the result must include, what it should avoid, and who reviews it. For a customer reply, that might mean an accurate summary, a specific next step, and a tone that sounds like your business. A review checklist helps the team recognize a plausible-looking answer that is still wrong or incomplete.'],
 ['Make room for editing','Treat the first AI response as a draft. Ask participants to identify assumptions, verify claims, and adjust the language. Compare the revised result with the original task. The useful skill is the full sequence—context, request, review, revision—not simply finding a clever prompt.'],
 ['Plan the follow-up','Choose a small task for the team to try after the workshop and collect questions as they use it. Dream Protocol’s starting workshop includes a two-hour remote session for up to five people, a prompt guide, and one 30-minute follow-up for $750. Larger groups and onsite delivery are quoted separately.']
 ],checklist:['One repeatable business task','Approved sample information','Access to the tools your business allows','A short output-review checklist','A task to practice after the session']},
 {slug:'crm-integration-checklist',title:'Before you connect AI to your CRM',category:'AI integrations',service:'ai-ready-it-projects',publishOn:'2026-09-28',status:'scheduled',description:'A practical checklist for letting an AI workflow create or update CRM records without losing context, duplicating customers, or hiding failures.',takeaway:'Define what the AI may read or write, how records are matched, and what happens when confidence or delivery fails.',sections:[
 ['Define the record before the connection','Decide whether a website submission creates a contact, lead, opportunity, task, or a combination. Map each form field to a destination and identify required values. A connection that technically delivers data can still create extra work if staff cannot tell what the record represents.'],
 ['Choose a source of truth','Agree on which system owns a field after it has been created. A returning customer may use a different phone number or company name. Decide whether the new submission updates the existing record, creates a review task, or stays separate until someone checks it.'],
 ['Handle repeated submissions deliberately','A visitor may press submit twice or send a second inquiry. Decide how the integration recognizes a repeated request and which information should be retained. Test this behavior with sample records before launch, including incomplete fields and different text formats.'],
 ['Know who receives the next task','A successful CRM update is only part of the workflow. Define assignment rules, notifications, and the expected next action. Make sure someone can see an inquiry that could not be assigned automatically. The connection should make ownership clearer to the team.'],
 ['Test delivery and recovery','Confirm API access and subscription requirements, then test ordinary and failed submissions. Agree on alerts, retry behavior, and a manual recovery path. Dream Protocol’s AI integration starting scope includes one approved AI-to-system connection, data mapping, error handling, and testing; additional systems or custom APIs are scoped separately.']
 ],checklist:['Destination record type','Required field mapping','Rules for existing contacts','Duplicate-request behavior','Assignment and failure owner']},
 {slug:'after-hours-call-handoffs',title:'Designing an after-hours call handoff',category:'AI front desk',service:'ai-front-desk',publishOn:'2026-10-05',status:'scheduled',description:'Define routine requests, urgent exceptions, and the information your team needs before using an AI front desk after hours.',takeaway:'An after-hours flow needs an agreed next step for both ordinary requests and exceptions.',sections:[
 ['Start with your actual availability','Document business hours, who is available outside them, and what a caller can reasonably expect. If the team is not staffed overnight, the agent should not promise an immediate callback. Approved wording should distinguish a received request from a confirmed appointment or dispatch.'],
 ['Identify the information that changes the handoff','Choose the fields your team needs to act: contact route, service requested, location, and the caller’s description. Avoid collecting unnecessary information. Where the service area matters, decide how the flow responds to requests outside it.'],
 ['Write the exception path','Agree on situations that require human escalation and the exact next step available. Test what happens when the designated person cannot be reached. Urgency rules should come from the business and its responsibilities rather than an improvised AI decision.'],
 ['Keep the message useful for staff','A handoff should tell the owner what was requested, which facts were supplied, and what remains uncertain. Avoid a long transcript as the only actionable record. When a connected system is involved, check where the summary appears and how staff know it is waiting.'],
 ['Revisit the flow when operations change','Update the approved information when hours, services, service areas, or staff responsibilities change. Review examples of difficult calls with the people who receive them. Improvements should be based on the real handoff problem, not simply making the conversation sound smoother.']
 ],checklist:['Accurate hours and availability','No unapproved response-time promise','Required callback information','Escalation and unavailable-person fallback','Named owner for the resulting request']},
 {slug:'ai-workflow-review',title:'A practical monthly AI workflow review',category:'Managed AI',service:'managed-ai-operations',publishOn:'2026-10-12',status:'scheduled',description:'Review changing business information, difficult requests, connections, and ownership without rebuilding everything.',takeaway:'Review the workflow against today’s business process, then test the changes that matter.',sections:[
 ['Check the business information first','Review hours, service descriptions, locations, contact routes, and the answers the workflow is allowed to give. Stale business information can make an otherwise functioning system unhelpful. Give each item an owner so changes have a route into the update process.'],
 ['Look at exceptions rather than only successes','Review a small set of requests that needed manual attention. Identify missing inputs, confusing routing, or unclear ownership. Separate issues caused by the process from issues caused by the connected tools. The right fix may be a clearer form field rather than a more complex prompt.'],
 ['Check system changes','Confirm whether subscriptions, permissions, field names, or downstream processes changed. Review how the workflow reports failures and who receives those reports. If a staff member moved roles, make sure the handoff still reaches someone responsible.'],
 ['Choose and test a bounded improvement','Describe the intended change, the expected behavior, and how you will check it. Include ordinary requests and the exception that motivated the change. Keep a way to return to the previous working behavior when a change does not produce the expected result.'],
 ['Record what was changed','Keep a brief change note and review any resulting effect on the team’s work. Dream Protocol’s managed support starting plan includes a monthly workflow review and up to four hours of support or improvements. Additional work is quoted before it starts, and new projects are scoped separately.']
 ],checklist:['Approved business information current','Exception examples reviewed','System access and ownership checked','Changes tested','A short record of the update']},
 {slug:'integration-vs-automation',title:'Integration or automation: which does your business need?',category:'Planning',service:'ai-ready-it-projects',publishOn:'2026-10-19',status:'scheduled',description:'Understand the difference between connecting data and coordinating work before scoping your next project.',takeaway:'Integration connects information. Automation coordinates actions. A useful project may need both.',sections:[
 ['Name the problem in everyday language','If staff repeatedly copy a customer record between systems, the immediate problem may be disconnected data. If nobody knows who follows up after the record arrives, the problem may be a missing process. Describe what goes wrong before deciding which technology label fits.'],
 ['What an integration does','An integration moves or synchronizes agreed information between systems. It needs field mapping, ownership rules, and a plan for missing or conflicting values. A website-to-CRM connection is a simple example: the incoming fields need a defined destination and a reliable delivery path.'],
 ['What an automation does','An automation coordinates a sequence after a trigger. A new inquiry may create a task, assign an owner, and prepare a follow-up. The rules for when those actions happen are part of the workflow. Not every step needs AI; a clear rule is often the right choice.'],
 ['Where they meet','A process may need an integration to deliver data and an automation to act on it. Make both responsibilities visible in the proposal. Otherwise a successful data transfer can be mistaken for a complete operational outcome even though a person still has to chase the next step.'],
 ['Start with a scoped outcome','Choose the systems, the trigger, and the desired handoff. Confirm API access and decide who handles exceptions. Dream Protocol scopes AI workflow automation and AI integrations explicitly so the model behavior, system actions, testing, and human handoff are clear.']
 ],checklist:['What information is disconnected?','What action is being missed?','Which system owns each field?','Which decisions need review?','What counts as a completed handoff?']},
 {slug:'business-ai-readiness',title:'Is your business ready for an AI project?',category:'Planning',service:'custom-ai-projects',publishOn:'2026-10-26',status:'scheduled',description:'Assess the task, information, people, and review process before investing in a custom AI tool.',takeaway:'You need a clear problem and usable information more than you need a long feature list.',sections:[
 ['Identify a person and a recurring problem','Choose who the tool is for and what is difficult about their current work. Bring an example of the task, the information available, and what a useful result would look like. A specific problem gives discovery something concrete to evaluate.'],
 ['Check the information available','An assistant cannot reliably answer from documents that are inaccessible, outdated, or contradictory. Identify the approved information, who maintains it, and what users are allowed to access. A document cleanup or ownership decision may be the most useful first step.'],
 ['Define the review point','Decide how a user can check the output and what happens when the tool is uncertain. Drafting, summarizing, and retrieving information have different review needs from taking an external action. Make those differences visible in the proposed workflow.'],
 ['Choose a first version you can evaluate','Limit the initial scope to a defined task or collection of information. Agree on examples that a useful system should handle and examples it should pass to a person. A smaller first version makes it easier to tell whether the approach is helping.'],
 ['Plan for ownership after launch','Decide who updates the information, reviews problems, and approves changes. Include handoff and ongoing support in the planning discussion. Dream Protocol’s custom projects begin with discovery and feasibility, followed by proposal-based milestones and deliverables.']
 ],checklist:['A named user and recurring task','Approved information with an owner','A way to check the result','A focused first version','A maintenance and handoff plan']}
];
