export const services = [
  {
    slug:'ai-front-desk', name:'AI receptionist', tag:'Never miss the call', icon:'◉',
    title:'AI Receptionist for Bay Area Businesses', headline:'Every call answered.\nEvery lead captured.',
    description:'AI voice reception that answers routine questions, captures intent, qualifies inquiries, routes urgent needs, and hands clean context to your team.',
    image:'dream-protocol-abstract.webp', price:'From $399', unit:'/ month', setup:'Setup from $995 for one business/location. Usage allowance and overages quoted upfront.',
    intro:'A missed call should not become a missed customer. Your AI receptionist learns the approved facts about your business, handles routine questions, captures the details your team needs, and follows the routing rules you approve.',
    points:[['Answer like your business','Use your approved services, hours, locations, FAQs, and policies so callers get a useful first answer instead of a generic bot response.'],['Capture useful context','Collect the reason for the call, contact details, location, urgency, and other fields your team actually needs before following up.'],['Route the right way','Define transfers, callback requests, escalation rules, and fallback behavior. Booking, CRM, and messaging connections are scoped where available.']],
    deliverables:['Business knowledge and call-flow setup','Agreed intake fields and routing rules','Testing of routine questions and difficult handoffs','Usage allowance, overages, and launch scope agreed upfront'],
    example:['A new customer calls after hours','The AI answers, identifies the service needed, captures the customer and location details, checks approved service-area rules, and sends the team a structured request for follow-up.'],
    faqs:[['Can it book appointments?','Yes when the scheduling system, API access, and business rules support it. Otherwise it can capture a complete booking request for staff review.'],['Can we keep our phone number?','Usually. We review your current phone provider, forwarding options, routing, and transfer requirements during setup.'],['Can it transfer to a person?','Yes when your phone setup supports it. We define transfer conditions, fallback behavior, and what happens if no one answers.'],['Is the website demo the production system?','No. The demo uses public website information. Production includes approved knowledge, call flows, testing, integrations, and an agreed launch scope.']],
    related:['ai-lead-engine','ai-scheduling-dispatch'], guide:'ai-receptionist-cost'
  },
  {
    slug:'ai-lead-engine', name:'AI lead engine', tag:'Respond while they are hot', icon:'✦',
    title:'AI Lead Response and Follow-Up for Bay Area Businesses', headline:'New lead.\nInstant next step.',
    description:'Respond to new leads, qualify them, follow up automatically, book next steps, update your CRM, and alert a person when the lead is ready.',
    image:'automation-art.webp', price:'From $499', unit:'/ month', setup:'Setup from $1,500 for one lead source and one follow-up path. CRM, SMS, email, and scheduling integrations are scoped based on your stack.',
    intro:'The fastest way to waste ad spend is to make a good lead wait. An AI lead engine watches the approved places new inquiries arrive, responds quickly, gathers missing context, follows up on a defined cadence, and moves qualified opportunities to the next step.',
    points:[['Respond immediately','Trigger from website forms, missed calls, inboxes, or other approved lead sources and send the first useful response without waiting for someone to notice it.'],['Qualify consistently','Ask the questions your team already uses to understand fit, urgency, budget, service area, or project type. Keep exceptions and sensitive decisions with a person.'],['Keep the opportunity moving','Send approved follow-ups, create CRM activity, request a booking, and alert the right person when the lead reaches a handoff point.']],
    deliverables:['One primary lead source and qualification flow','Approved email or SMS follow-up sequence','Lead routing and human handoff rules','Basic CRM or scheduling connection where feasible','30-day launch tuning for the agreed scope'],
    example:['A website lead arrives at 9:42 PM','The lead gets an immediate response, answers two qualifying questions, receives a booking link or callback option, and appears in the CRM with the conversation context ready for the sales team.'],
    faqs:[['Can it text leads?','Yes when an approved messaging provider, consent requirements, and your business rules are in place. Usage fees are separate where applicable.'],['Will it replace our salesperson?','No. The system handles speed, consistency, qualification, and routine follow-up. Your team handles judgment, negotiation, and the relationship.'],['Can it revive old leads?','Yes as a separately scoped campaign when you have an appropriate contact list, approved messaging, and a defined re-engagement offer.']],
    related:['ai-front-desk','workflow-automation'], guide:'choose-first-automation'
  },
  {
    slug:'ai-scheduling-dispatch', name:'AI scheduling & dispatch', tag:'Book and route the work', icon:'⌁',
    title:'AI Scheduling and Dispatch Automation for Bay Area Businesses', headline:'From request.\nTo booked and routed.',
    description:'Turn calls and inquiries into scheduled work with availability checks, booking rules, confirmations, reminders, dispatch context, and human exceptions.',
    image:'automation-art.webp', price:'From $2,500', unit:'/ project', setup:'One scheduling or dispatch workflow. Calendar, field-service, CRM, or dispatch-system compatibility is confirmed before scope.',
    intro:'Scheduling gets expensive when staff spend the day bouncing between phones, calendars, technicians, and customers. We build a defined path from request to available next step, with the exceptions and promises kept under your control.',
    points:[['Know what can be booked','Define service types, durations, service areas, working hours, lead times, resource rules, and the situations that require staff review.'],['Connect availability','Use an approved calendar, scheduling platform, or field-service system to check or request time without creating duplicate or impossible bookings.'],['Prepare dispatch context','Carry the customer, location, issue, appointment, notes, and urgency into the handoff so the next person does not have to start over.']],
    deliverables:['One defined scheduling or dispatch workflow','Booking rules and exception handling','Calendar or scheduling integration where feasible','Confirmation/reminder logic within scope','Testing and 30-day fixes for the agreed build'],
    example:['A customer needs service tomorrow','The system identifies the service type and location, checks the approved scheduling rules, offers the supported next step, confirms the request, and passes clean dispatch context into the connected system.'],
    faqs:[['Can it dispatch technicians automatically?','It can when your field-service system, routing rules, and operational requirements support it. We confirm those constraints before promising automatic dispatch.'],['Can it send reminders?','Yes. Email or SMS reminders can be included when the messaging system and consent requirements are available.'],['What if the schedule is complicated?','Complex routing, skills, territories, parts, travel time, and multi-resource requirements are scoped as a larger project.']],
    related:['ai-front-desk','workflow-automation'], guide:'choose-first-automation'
  },
  {
    slug:'workflow-automation', name:'Workflow automation', tag:'Make repetitive work disappear', icon:'↗',
    title:'Workflow Automation for Bay Area Businesses', headline:'Trigger. Decide.\nMove the work.',
    description:'Automate repetitive business processes across forms, email, CRM, tasks, approvals, notifications, and connected systems.',
    image:'automation-art.webp', price:'From $1,500', unit:'/ project', setup:'One workflow across up to two existing tools. Testing, documentation, handoff, and 30-day fixes for the agreed scope.',
    intro:'Repeated copy-and-paste, forgotten follow-ups, duplicate entry, and unclear ownership usually mean the process needs a better path. We map the trigger, required information, decisions, exceptions, and next action before automating it.',
    points:[['Map the real process','Identify where work starts, what a complete record looks like, who owns each decision, and where exceptions currently get stuck.'],['Automate the boring middle','Move information, create records and tasks, prepare messages, update status, and connect the approved systems that already run the business.'],['Keep exceptions visible','Define alerts, retries, review points, and manual fallback so unusual work does not disappear inside an automation.']],
    deliverables:['One defined workflow across up to two existing tools','Agreed rules, data fields, and review points','Testing, documentation, and staff handoff','30-day fixes for the agreed scope'],
    example:['A customer request becomes a complete work item','The request is classified, the customer record is created or updated, a task goes to the right owner, missing information is flagged, and the next approved message is prepared automatically.'],
    faqs:[['Does every workflow need AI?','No. Deterministic rules are often better for predictable steps. We use AI when interpretation, classification, extraction, or drafting adds value.'],['What if a connection fails?','Error handling is scoped with the workflow. We define alerts, retries where appropriate, and who owns manual recovery.'],['Are software subscriptions included?','No. Software licenses, third-party usage, custom APIs, and data cleanup are quoted separately where needed.']],
    related:['ai-document-automation','ai-ready-it-projects'], guide:'choose-first-automation'
  },
  {
    slug:'ai-document-automation', name:'AI document automation', tag:'Stop retyping documents', icon:'▤',
    title:'AI Document Processing Automation for Bay Area Businesses', headline:'PDF in.\nUseful data out.',
    description:'Extract, classify, summarize, validate, and route information from PDFs, forms, invoices, purchase orders, applications, and email attachments.',
    image:'integration-art.webp', price:'From $2,500', unit:'/ workflow', setup:'One document type and one destination workflow. OCR quality, document variability, validation rules, and system access are reviewed before scope.',
    intro:'A surprising amount of office work is still someone opening a document, reading fields, typing them somewhere else, and sending an email. Document automation turns that manual handoff into a controlled process with extraction, validation, review, and routing.',
    points:[['Read the document','Classify incoming files and extract the fields, dates, totals, names, line items, or other information the workflow needs.'],['Validate before action','Check required fields, confidence thresholds, duplicates, totals, formats, and business rules. Send uncertain cases to a person instead of guessing.'],['Send the data somewhere useful','Create or update records, rename and store files, prepare follow-ups, or route the document into the next approved business process.']],
    deliverables:['One defined document type and intake path','Field extraction and validation rules','One target system or downstream workflow','Low-confidence human review path','Testing and 30-day fixes for the agreed scope'],
    example:['An emailed invoice arrives','The workflow identifies the vendor and invoice details, validates required fields, flags anything uncertain, stores the file correctly, and prepares the accounting record or review task.'],
    faqs:[['Can it read scanned PDFs?','Often, yes. Accuracy depends on scan quality, handwriting, layout consistency, and the fields required. We test representative samples before committing to the workflow.'],['Can it process sensitive documents?','Potentially, but data handling, approved systems, access controls, and contractual requirements must be reviewed before implementation.'],['Can it handle many document types?','Yes, but each additional type increases testing and exception handling. Multi-document systems are scoped as a larger project.']],
    related:['workflow-automation','ai-ready-it-projects'], guide:'crm-integration-checklist'
  },
  {
    slug:'ai-knowledge-agent', name:'AI knowledge agent', tag:'Your company answers itself', icon:'◎',
    title:'Internal AI Knowledge Assistants for Bay Area Businesses', headline:'Ask your business.\nGet the approved answer.',
    description:'Give employees an AI assistant grounded in approved SOPs, policies, manuals, documents, and internal knowledge with citations and access controls.',
    image:'dream-protocol-abstract.webp', price:'From $3,500', unit:'/ project', setup:'One initial knowledge collection and one user experience. Data sources, permissions, update process, and answer-verification requirements are scoped first.',
    intro:'The answer is often somewhere inside the company, buried in a SharePoint folder, PDF, SOP, handbook, or old document. A knowledge agent gives staff a faster way to find approved information while keeping the source visible.',
    points:[['Ground it in approved knowledge','Start with a defined document collection or connected source and decide which information is authoritative enough to answer from.'],['Keep the source visible','Return answers with citations or source links so employees can verify the underlying policy, procedure, or document instead of trusting an unsupported response.'],['Control who can see what','Scope user access, source permissions, update rules, and the situations where the assistant should say it does not know.']],
    deliverables:['One approved knowledge collection','Grounded answer experience with source references','Access and update rules for the agreed scope','Testing against real employee questions','Handoff documentation and support options'],
    example:['An employee asks how to process a return','The assistant answers from the approved SOP, cites the relevant section, and points the employee to the current source document instead of inventing a process.'],
    faqs:[['Can it connect to SharePoint or Google Drive?','Often, yes. Feasibility depends on the source, API access, permissions, identity model, and how current the knowledge needs to be.'],['Does it train the AI on our private data?','The architecture and data flow are reviewed during scoping. We choose an implementation that matches the approved systems and handling requirements.'],['What happens when the answer is not in the documents?','The assistant should say it does not have an approved answer and route the user to the right person or source.']],
    related:['ai-ready-it-projects','managed-ai-operations'], guide:'choose-first-automation'
  },
  {
    slug:'ai-automation-assessment', name:'AI automation assessment', tag:'Find the best first move', icon:'⌕',
    title:'AI Automation Assessment for Bay Area Businesses', headline:'Where should AI\nactually start?',
    description:'A focused review of your workflows, systems, bottlenecks, and automation opportunities with a prioritized action plan instead of a generic AI brainstorm.',
    image:'dream-protocol-abstract.webp', price:'$750', unit:'/ assessment', setup:'Remote assessment covering up to three business workflows, current tools, major constraints, and recommended next steps.',
    intro:'If you know AI could help but do not know where the first dollar should go, start here. We look at the work your people repeat, the systems involved, the handoffs that fail, and the places where speed or consistency matter enough to automate.',
    points:[['Find the expensive friction','Review up to three workflows and identify repetitive work, delays, missed follow-up, duplicate entry, search time, and other operational drag.'],['Separate real automation from AI theater','Identify which steps need AI, which are better handled with normal automation, which depend on integration, and which should stay human.'],['Leave with an ordered plan','Get prioritized opportunities, likely dependencies, key risks, and recommended starting scopes so you can decide what is worth building first.']],
    deliverables:['Remote review of up to three workflows','Current-system and dependency map','Prioritized automation opportunity list','Recommended first project and next-step scope','Written assessment summary'],
    example:['Three annoying processes compete for budget','We compare missed-call intake, quote follow-up, and invoice entry, identify the cost and technical path of each, and recommend the first automation based on value, complexity, and risk.'],
    faqs:[['Is this just a sales call?','No. It is a paid working session with a written assessment. The goal is to identify where automation is worth pursuing and where it is not.'],['Do we need to know what AI tool we want?','No. Start with the business process, current systems, examples, and pain points. Tool selection comes after the workflow is understood.'],['Does the assessment include implementation?','No. Implementation is scoped separately after you decide which opportunity to pursue.']],
    related:['workflow-automation','custom-ai-projects'], guide:'choose-first-automation'
  },
  {
    slug:'ai-ready-it-projects', name:'Systems integration', tag:'Make your tools talk', icon:'⌘',
    title:'Business Systems Integration in the Bay Area', headline:'One business.\nLess swivel-chair work.',
    description:'Connect business systems with clear data mapping, source-of-truth rules, error handling, testing, and maintainable APIs.',
    image:'integration-art.webp', price:'From $2,500', unit:'/ connection', setup:'One scoped connection between two systems. Data mapping, error handling, testing, and 30-day fixes for the agreed scope.',
    intro:'Your tools may work well individually while your people spend the day moving the same information between them. We define ownership, map the data, confirm the APIs, and build a reliable connection around the process.',
    points:[['Define the source of truth','Agree on which system owns contacts, appointments, jobs, requests, documents, or status before data starts moving.'],['Confirm the technical path','Review APIs, webhooks, authentication, licensing, rate limits, and the constraints that determine whether the connection is actually viable.'],['Make failure visible','Test missing fields, duplicates, interrupted requests, and bad inputs. Build the alerts and recovery steps needed to operate the connection.']],
    deliverables:['One scoped connection between two systems','Data mapping and ownership rules','Error handling and functional testing','Documentation and 30-day fixes for the agreed scope'],
    example:['A website lead becomes a CRM opportunity','Contact and inquiry data map into the correct fields, duplicate handling follows explicit rules, and errors create an alert instead of silently dropping the lead.'],
    faqs:[['Can you connect our specific software?','We review the product, subscription tier, available API, authentication, and the workflow you need before confirming feasibility.'],['Does integration include data cleanup?','Data cleanup, historical migration, custom APIs, and additional systems are quoted separately.'],['What is the difference from automation?','Integration moves data between systems. Automation coordinates business steps. Many useful projects include both.']],
    related:['workflow-automation','ai-document-automation'], guide:'crm-integration-checklist'
  },
  {
    slug:'ai-training', name:'AI team training', tag:'Make your people better with AI', icon:'✳',
    title:'AI Training Workshops for Bay Area Teams', headline:'Stop guessing.\nUse AI on real work.',
    description:'Practical AI workshops built around the work your team already does, with review habits, reusable prompts, and clear boundaries.',
    image:'training-art.webp', price:'$750', unit:'/ workshop', setup:'Two-hour remote session for up to five people. Larger teams and onsite delivery quoted separately.',
    intro:'The useful question is not whether AI can write an email. It is whether your team knows where AI saves time, what context to provide, how to review the result, and when a human still needs to decide.',
    points:[['Use your real tasks','Work on customer replies, summaries, research, internal instructions, document review, or other agreed tasks from the team’s actual day.'],['Build review into the habit','Practice checking facts, omissions, tone, assumptions, and sensitive information instead of treating AI output as finished work.'],['Leave with a repeatable playbook','Turn the best exercises into reusable prompts and a review guide your team can continue using after the session.']],
    deliverables:['Two-hour remote workshop for up to five people','Exercises around agreed business tasks','Reusable prompt guide','One 30-minute follow-up'],
    example:['A recurring admin task becomes a repeatable AI workflow','The team learns what context the model needs, how to ask for the output, what to verify, and when the work must stay with a person.'],
    faqs:[['Do we need technical experience?','No. We start from the team’s actual work and current comfort level.'],['Can you train a larger group onsite?','Yes. Larger teams and onsite sessions are quoted separately based on group size, location, and the tasks involved.'],['Does a workshop include building an automation?','No. The workshop focuses on skills. Automation and integration builds are scoped separately.']],
    related:['ai-knowledge-agent','workflow-automation'], guide:'first-ai-workshop'
  },
  {
    slug:'managed-ai-operations', name:'Managed AI operations', tag:'Keep it working', icon:'◌',
    title:'Managed AI Operations for Bay Area Businesses', headline:'AI is not set-and-forget.\nKeep it sharp.',
    description:'Ongoing review, tuning, maintenance, usage checks, knowledge updates, and scoped improvements for the AI systems running your business.',
    image:'dream-protocol-abstract.webp', price:'From $750', unit:'/ month', setup:'Up to four hours of support or improvements, plus a monthly workflow review. Additional work quoted before it starts.',
    intro:'Business processes, software, hours, services, prices, staff, and customer questions all change. Managed AI operations keeps the systems you launched aligned with the business they are supposed to support.',
    points:[['Review real behavior','Look at what changed, where users get stuck, where the workflow is weak, and which updates are worth making.'],['Tune safely','Adjust approved knowledge, prompts, rules, routing, integrations, or workflow behavior within the agreed support scope and test before release.'],['Know the boundary','The starting plan includes up to four hours of support or improvements. Bigger changes and new systems receive a separate quote.']],
    deliverables:['Monthly review of the agreed AI systems','Up to four hours of support or improvements','Testing of scoped updates','Separate quotes for work beyond the plan'],
    example:['Your scheduling rules change','We update the relevant workflow, test routine and edge cases, confirm the handoff behavior, and document the change before it becomes part of production.'],
    faqs:[['Is this included with the AI receptionist?','No. Managed operations is a separate plan unless your proposal explicitly includes ongoing support.'],['Does the plan include unlimited support?','No. The starting plan includes up to four hours. Additional work is quoted before it starts.'],['Can you support a system built elsewhere?','Possibly. We first review the architecture, documentation, access, and current condition before accepting support responsibility.']],
    related:['ai-front-desk','ai-knowledge-agent'], guide:'ai-workflow-review'
  },
  {
    slug:'custom-ai-projects', name:'Custom AI builds', tag:'Build what does not exist yet', icon:'◇',
    title:'Custom AI Projects for Bay Area Businesses', headline:'Bigger idea.\nBuild the useful version first.',
    description:'Custom AI tools, internal copilots, agentic workflows, customer experiences, data products, and business-specific automation.',
    image:'integration-art.webp', price:'From $750', unit:'/ discovery', setup:'Paid discovery starts at $750. Build pricing follows a scoped proposal with milestones, deliverables, testing, and support options.',
    intro:'Some ideas do not fit a package. A custom tool, internal copilot, unusual workflow, or new customer experience may need its own architecture. We start with a focused discovery so you can evaluate feasibility before committing to a build.',
    points:[['Find the valuable first version','Identify the users, problem, data, systems, decisions, and success criteria. Cut the idea down to the smallest version that can prove value.'],['Check feasibility before build','Review model requirements, system access, APIs, security, data quality, latency, operating cost, and the human decisions that cannot be delegated.'],['Build in clear phases','Agree on milestones, test criteria, deployment, handoff, and support before expanding beyond the first useful version.']],
    deliverables:['Paid discovery and feasibility review','Scoped proposal with architecture and milestones','Agreed build, testing, and handoff deliverables','Support options scoped separately'],
    example:['A company wants an internal operations copilot','Discovery identifies the approved data sources, user workflows, permissions, integrations, and the first set of tasks worth automating before a production build begins.'],
    faqs:[['Can we start with an idea instead of a specification?','Yes. Bring the problem, users, current process, and examples. Discovery turns that into an assessable scope.'],['Do you guarantee the idea is feasible?','No. Feasibility depends on the systems, data, constraints, and required reliability. Discovery exists to answer that before a larger commitment.'],['How much does the full build cost?','It depends on integrations, data, security, user experience, testing, and operational requirements. You receive a scoped proposal after discovery.']],
    related:['ai-ready-it-projects','ai-knowledge-agent'], guide:'choose-first-automation'
  }
];

export const industries = [
 {slug:'ai-receptionist-for-home-services',name:'Home services',title:'AI for Bay Area Home Service Businesses',headline:'Keep the work moving.\nEven when you’re on a job.',description:'AI reception, scheduling, dispatch, and workflow automation for plumbers, HVAC teams, electricians, and other Bay Area home service businesses.',need:'When the crew is on site, the next customer still needs an answer. Capture the request, qualify urgency, schedule the supported next step, and hand dispatch clean context.',steps:[['Capture the essentials','Ask for the service need, job location, callback details, and the facts dispatch needs. Check approved service-area rules before promising a next step.'],['Schedule what is safe to schedule','Use approved service types, availability, lead times, and exception rules. Keep complicated or urgent cases with dispatch.'],['Prepare the handoff','Send customer, property, issue, timing, and urgency context into the connected dispatch or field-service process.']],example:'A caller reports a water-heater leak. The AI captures the address and issue, follows approved urgency rules, requests or books the supported appointment path, and hands dispatch the full context.',primary:'ai-scheduling-dispatch',secondary:'ai-front-desk',faq:['Can it quote a repair?','Only approved pricing information can be used. Work requiring inspection or diagnosis should be handed to your team.']},
 {slug:'industries/professional-services',name:'Professional services',title:'AI for Bay Area Professional Service Firms',headline:'More client work.\nLess administrative drag.',description:'AI lead response, inquiry routing, knowledge agents, document workflows, and team training for Bay Area professional firms.',need:'Professional teams lose time qualifying inquiries, preparing routine communications, searching internal knowledge, and moving information between systems. Those are strong places to automate without delegating professional judgment.',steps:[['Respond to inquiries faster','Collect service need, company context, contact details, and qualification information before a person reviews the opportunity.'],['Find internal answers faster','Ground an employee assistant in approved procedures, templates, policies, and internal documents with source references.'],['Automate the admin path','Create tasks, update CRM records, prepare drafts, and move approved information while professional decisions stay with staff.']],example:'A prospective client submits an inquiry. The AI qualifies the request, prepares a structured intake, creates the CRM activity, and alerts the right person with the context already organized.',primary:'ai-lead-engine',secondary:'ai-knowledge-agent',faq:['Can AI make professional decisions for us?','No. The system can support administrative work, research from approved sources, intake, and drafts. Qualified staff retain professional judgment and final review.']},
 {slug:'industries/tax-accounting',name:'Tax & accounting',title:'AI Workflows for Bay Area Tax and Accounting Firms',headline:'Documents in.\nOrganized work out.',description:'Document automation, administrative workflows, knowledge agents, and team training for Bay Area CPA, tax, and bookkeeping firms.',need:'Document requests, intake checklists, invoice processing, status follow-up, and repetitive data entry can consume an accounting team’s attention. Start with a defined administrative workflow and approved systems.',steps:[['Process documents','Extract agreed fields from forms, statements, invoices, or other approved document types and route uncertain cases for human review.'],['Automate follow-up','Use status changes and missing-information rules to prepare reminders, staff tasks, and customer requests.'],['Keep judgment human','Use AI for administrative organization and drafting while tax positions, accounting judgments, and final advice stay with qualified professionals.']],example:'A new-client document arrives. The workflow classifies it, extracts the agreed fields, flags low-confidence data, attaches it to the correct process, and creates the next staff task.',primary:'ai-document-automation',secondary:'workflow-automation',faq:['Should we put client financial records into the website demo?','No. The public demo uses public website information. Client-data workflows require a separate review of approved systems, access, and handling requirements.']},
 {slug:'industries/property-management',name:'Property & facilities',title:'AI for Bay Area Property and Facilities Teams',headline:'Every request.\nBooked, routed, visible.',description:'AI maintenance intake, scheduling, dispatch, document workflows, and automation for Bay Area property managers and facilities teams.',need:'A maintenance request is useful when the team knows the property, issue, contact details, urgency, and next step. Build intake and dispatch around the information required to act.',steps:[['Collect the right context','Identify the property or unit, reported issue, contact route, access notes, and required fields for a complete request.'],['Schedule or route by rule','Use property, issue type, urgency, vendor responsibility, and approved scheduling rules to prepare the correct handoff.'],['Keep emergencies explicit','Use office-approved escalation language. The AI organizes and routes information; staff or emergency services make the response decision.']],example:'A tenant reports a heating problem. The AI captures the unit and issue, follows approved urgency rules, requests or schedules the supported next step, and routes a complete maintenance ticket.',primary:'ai-scheduling-dispatch',secondary:'ai-front-desk',faq:['Can this connect to our property software?','We assess the product, API access, subscription tier, authentication, and required workflow before confirming an integration.']},
 {slug:'industries/retail-hospitality',name:'Retail & hospitality',title:'AI for Bay Area Retail and Hospitality Businesses',headline:'More customers helped.\nLess front-desk chaos.',description:'AI reception, lead response, booking support, staff knowledge, and connected workflows for Bay Area shops, venues, restaurants, and hospitality businesses.',need:'Customers ask the same questions, submit event inquiries, request reservations, and need follow-up while your staff are serving the people in front of them. AI can absorb that routine load.',steps:[['Answer routine questions','Use approved information about hours, locations, services, policies, and common questions.'],['Capture revenue opportunities','Qualify event, group, service, or special-request leads and follow up on the approved path.'],['Connect bookings selectively','Integrate reservation or scheduling systems where the APIs and business rules support a dependable flow.']],example:'A customer asks about a private event. The AI answers approved questions, captures date and group details, qualifies the request, and starts the follow-up path for the events team.',primary:'ai-lead-engine',secondary:'ai-front-desk',faq:['Can it confirm a reservation or inventory?','Only when a suitable live system connection and tested business rules support it. Otherwise it can collect and route a request for staff review.']},
 {slug:'industries/medical-dental',name:'Medical & dental',title:'Administrative AI for Bay Area Medical and Dental Offices',headline:'Support the front office.\nKeep care with your team.',description:'AI reception, scheduling support, administrative follow-up, and staff knowledge workflows for Bay Area medical and dental offices.',need:'Start with non-clinical tasks such as office information, appointment requests, callback routing, reminders, and staff knowledge. Any workflow involving patient information requires a separate review of approved systems and handling requirements.',steps:[['Define the administrative scope','Choose the office information and request types the AI can handle. Avoid clinical advice and unapproved collection of sensitive information.'],['Support scheduling','Use approved scheduling rules and connected systems where available, or route a complete appointment request to staff.'],['Keep care decisions human','Use office-approved escalation language. Clinical advice, urgent medical concerns, and patient-care decisions stay with appropriate professionals.']],example:'A prospective patient asks for an appointment. The AI provides approved office information, captures the administrative request, uses the supported scheduling path, and routes exceptions to staff.',primary:'ai-front-desk',secondary:'ai-scheduling-dispatch',faq:['Is patient-data handling included by default?','No. Systems, contracts, access controls, and patient-data handling requirements must be assessed separately before a patient-information workflow is implemented.']}
];
