export const services = [
  {
    slug:'ai-front-desk', name:'AI front desk', tag:'Answer & route', icon:'◉',
    title:'AI Receptionist for Bay Area Businesses', headline:'A better first hello.\nA clearer next step.',
    description:'An AI receptionist shaped around your business: answer routine questions, capture inquiries, and hand the right details to your team.',
    image:'dream-protocol-abstract.webp', price:'From $399', unit:'/ month', setup:'Setup from $995 for one business/location. Usage allowance and overages quoted upfront.',
    intro:'A missed call can leave a customer without a next step. An AI front desk gives callers a way to explain what they need, get approved business information, and leave a useful request for your staff. We design the conversation around your services, hours, service area, and handoff rules.',
    points:[['Business knowledge','Build from the services, hours, locations, and answers you approve. Decide which questions the agent can answer and which belong with a person.'],['Useful intake','Capture the contact details and context your team needs. Define the difference between a new inquiry, an existing customer, and an urgent request.'],['Human handoff','Agree on routing, fallback behavior, and escalation before launch. Calendar, CRM, and messaging connections depend on the systems and access available.']],
    deliverables:['Business knowledge and call-flow setup','Agreed intake fields and routing rules','Testing of routine questions and difficult handoffs','Usage allowance, overages, and launch scope agreed upfront'],
    example:['A service inquiry arrives','The caller explains the problem and location. The agent checks the approved service area, captures callback details, and passes a structured request to the team. Staff decide availability and the next action.'],
    faqs:[['Can it book appointments?','Booking depends on your calendar, available APIs, and scheduling rules. We confirm the integration before promising a booking flow; a callback request can be the starting point.'],['Can we keep our phone number?','We review your current phone provider and routing options during scoping. Number changes, forwarding, and transfers depend on that setup.'],['Does it replace our staff?','It handles the routine part of intake you choose. Your staff keep control of exceptions, professional judgment, and the final customer relationship.'],['Is the demo our production system?','No. The website demo illustrates a conversation using information found on your website. A production launch includes approved knowledge, configuration, testing, and a separately agreed scope.']],
    related:['workflow-automation','managed-ai-operations'], guide:'ai-receptionist-cost'
  },
  {
    slug:'ai-training',name:'AI training',tag:'Build team confidence',icon:'✳',title:'AI Training Workshops for Bay Area Teams',headline:'Make AI part of\na better workday.',
    description:'Practical AI workshops for Bay Area businesses. Work on real tasks, learn to review the output, and leave with a guide your team can use.',image:'training-art.webp',price:'$750',unit:'/ workshop',setup:'Two-hour remote session for up to five people. Larger teams and onsite delivery quoted separately.',
    intro:'The useful question is not whether AI can write an email. It is whether your people know when to use it, what information to provide, and how to check the result. Our workshops start with the work your team already does and turn it into repeatable practice.',
    points:[['Start with real work','Choose tasks such as customer replies, meeting summaries, internal instructions, or first drafts. We agree on your tools and the team’s starting point before the session.'],['Build review into the habit','Practice checking facts, tone, omissions, and assumptions. Discuss which information belongs in your approved tools and when a person needs to make the decision.'],['Keep learning after the session','Leave with a prompt guide and one 30-minute follow-up. Use that conversation to discuss what worked, what felt difficult, and where the team needs a clearer process.']],
    deliverables:['Two-hour remote workshop for up to five people','Exercises around agreed business tasks','Reusable prompt guide','One 30-minute follow-up'],
    example:['A customer email becomes a useful draft','The team provides the approved background, asks for a draft, checks factual details, and adjusts the tone before sending. The exercise becomes a repeatable prompt with a review checklist.'],
    faqs:[['Do we need technical experience?','No. We agree on your team’s starting point and use business tasks as the basis for the session.'],['Can you train a larger group onsite?','Yes, larger teams and onsite sessions are quoted separately. Tell us your location, group size, and the tasks you want to practice.'],['Does a workshop include building an automation?','The workshop focuses on team skills. Workflow builds and systems integration are scoped separately.']],related:['workflow-automation','ai-ready-it-projects'],guide:'first-ai-workshop'
  },
  {
    slug:'workflow-automation',name:'Workflow automation',tag:'Give time back',icon:'↗',title:'Workflow Automation for Bay Area Businesses',headline:'Less chasing.\nMore moving forward.',
    description:'Connect the steps between a request and its next action. Workflow automation for Bay Area teams, with clear rules, testing, and human review.',image:'automation-art.webp',price:'From $1,500',unit:'/ project',setup:'One workflow across up to two existing tools. Testing, documentation, handoff, and 30-day fixes for the agreed scope.',
    intro:'Repeated copy-and-paste, forgotten follow-ups, and unclear ownership all point to the same opportunity: a better process. We map the trigger, required information, decisions, and next action before building the automation around your existing tools.',
    points:[['Map the work first','Identify where the request starts, what a complete record looks like, who owns it, and which decisions need review. Simplify unclear steps before automating them.'],['Connect the right steps','Move information between approved systems, organize incoming requests, create tasks, and prepare follow-ups. Confirm compatibility and permissions during discovery.'],['Plan for exceptions','Define what happens when information is missing, a connection fails, or a request falls outside the usual path. Make the owner and recovery process explicit.']],
    deliverables:['One defined workflow across up to two existing tools','Agreed rules, data fields, and review points','Testing, documentation, and staff handoff','30-day fixes for the agreed scope'],
    example:['A new inquiry reaches the right owner','A submitted inquiry creates a CRM record, prepares a task for the responsible team, and flags missing information. A person reviews the context before any sensitive or unusual response.'],
    faqs:[['Does every workflow need AI?','No. Clear rules are often enough. We use AI where interpretation or drafting is useful and keep straightforward steps deterministic.'],['What if a connection fails?','Error handling is scoped with the workflow. We agree on alerts, retries where appropriate, and who handles a request that needs manual attention.'],['Are software subscriptions included?','Software licenses, third-party usage, custom APIs, and data cleanup are quoted separately where needed.']],related:['ai-ready-it-projects','managed-ai-operations'],guide:'choose-first-automation'
  },
  {
    slug:'ai-ready-it-projects',name:'Systems integration',tag:'Connect your business',icon:'⌘',title:'Business Systems Integration in the Bay Area',headline:'Your tools.\nWorking together.',
    description:'Connect business systems with clear data mapping, error handling, and testing. Integration projects for businesses across the San Francisco Bay Area.',image:'integration-art.webp',price:'From $2,500',unit:'/ project',setup:'One scoped connection between two systems. Data mapping, error handling, testing, and 30-day fixes for the agreed scope.',
    intro:'Your tools may work well individually while information gets lost between them. We review the systems you rely on, define where each piece of information belongs, and build a scoped connection that supports the way your team works.',
    points:[['Define the source of truth','Agree on which system owns contacts, appointments, requests, or status updates. Map fields and resolve conflicting formats before connecting data.'],['Confirm the connection','Review available APIs, account permissions, licensing, and technical limits. Compatibility is confirmed during discovery rather than assumed from a software logo.'],['Make the handoff dependable','Test missing fields, duplicate records, and interrupted requests. Document how the connection works and what the team should do when it needs attention.']],
    deliverables:['One scoped connection between two systems','Data mapping and ownership rules','Error handling and functional testing','Documentation and 30-day fixes for the agreed scope'],
    example:['A website inquiry becomes a CRM record','Name, company, and inquiry details map into the agreed CRM fields. Duplicate handling and missing values follow explicit rules, so staff can work from a consistent record.'],
    faqs:[['Can you connect our specific software?','We first review the product, subscription tier, API access, and the workflow you need. Tell us the tools involved so we can assess feasibility.'],['Does integration include data cleanup?','Data cleanup, custom APIs, and additional systems are quoted separately. We identify these needs before agreeing on the build.'],['What is the difference from automation?','Integration connects systems and their data. Automation coordinates the steps in a process. Some projects need both, and the proposal makes that scope clear.']],related:['workflow-automation','managed-ai-operations'],guide:'crm-integration-checklist'
  },
  {
    slug:'managed-ai-operations',name:'Managed AI support',tag:'Keep improving',icon:'◎',title:'Managed AI Support for Bay Area Businesses',headline:'Launch is a beginning.\nKeep getting better.',
    description:'Ongoing reviews, maintenance, and scoped improvements for existing AI workflows. Managed AI support for San Francisco Bay Area businesses.',image:'dream-protocol-abstract.webp',price:'From $750',unit:'/ month',setup:'Up to four hours of support or improvements, plus a monthly workflow review. Additional work quoted before it starts.',
    intro:'Business processes change. So do hours, services, software, and the questions your customers ask. Managed support gives your existing AI workflows a regular review and a practical path for updates, with a clear scope for the work.',
    points:[['Review what changed','Discuss new business requirements, changed processes, and the parts of the workflow that need attention. Choose improvements based on the actual work.'],['Make controlled updates','Adjust approved knowledge, routing, or workflow behavior within the agreed support scope. Test changes before putting them into use.'],['Know what is included','The starting plan includes up to four hours of support or improvements and a monthly workflow review. Larger changes and new builds receive a separate quote.']],
    deliverables:['Monthly review of the agreed workflow','Up to four hours of support or improvements','Testing of scoped updates','Separate quotes for work beyond the plan'],
    example:['Your service process changes','The team brings an updated intake requirement. We agree on the change, update the workflow within scope, and check routine and exception cases before handoff.'],
    faqs:[['Is this included with the AI front desk?','Managed support is a separate service from the published front-desk plan. The proposal specifies the support included in your setup.'],['Does the plan include unlimited support?','No. The starting plan includes up to four hours of support or improvements. Additional work is quoted before it starts.'],['Can you support a workflow built elsewhere?','We review the existing setup, documentation, and access before confirming a support scope.']],related:['ai-front-desk','workflow-automation'],guide:'ai-workflow-review'
  },
  {
    slug:'custom-ai-projects',name:'Custom AI projects',tag:'Build what comes next',icon:'✧',title:'Custom AI Projects for Bay Area Businesses',headline:'A bigger idea.\nA practical way forward.',
    description:'Explore custom AI tools, knowledge assistants, and business workflows. Start with discovery, feasibility, and a clear build plan.',image:'integration-art.webp',price:'Let’s scope it',unit:'',setup:'Proposal-based pricing. Discovery, milestones, deliverables, and ongoing support are agreed for each project.',
    intro:'Some ideas do not fit a package. An internal knowledge assistant, a focused business tool, or a new way to coordinate work may need its own design. We start by understanding the users, the information involved, and the outcome you want to improve.',
    points:[['Find the useful first version','Identify who will use the tool, what they need to do, and what success would look like. Choose a focused starting point that can be evaluated.'],['Check feasibility early','Review data access, system connections, operational constraints, and the decisions that need human involvement before committing to the build.'],['Build in clear phases','Agree on milestones, deliverables, testing, and ownership. Scope ongoing support separately so you know what happens after launch.']],
    deliverables:['Discovery and feasibility review','A scoped proposal and phased milestones','Agreed build, test, and handoff deliverables','Support options scoped separately'],
    example:['An internal knowledge assistant','A team wants to find approved process information more easily. The first version is scoped around a defined collection of documents, access rules, and a way to verify the answers.'],
    faqs:[['Can we start with an idea rather than a specification?','Yes. Bring the problem, the people affected, and examples of the current process. Discovery helps turn the idea into an assessable scope.'],['Do you guarantee an idea is feasible?','No. Feasibility depends on the systems, information, and requirements involved. We assess those before proposing a build.'],['Who maintains the project after launch?','Handoff and support arrangements are agreed in the proposal. Ongoing managed support is scoped separately.']],related:['ai-ready-it-projects','ai-training'],guide:'choose-first-automation'
  }
];

export const industries = [
 {slug:'ai-receptionist-for-home-services',name:'Home services',title:'AI for Bay Area Home Service Businesses',headline:'Keep the work moving.\nEven when you’re on a job.',description:'AI intake and workflow automation for plumbers, HVAC teams, electricians, and other Bay Area home service businesses.',need:'When the crew is on site, the next customer may still need an answer. Start with structured service intake and a clear route to the person who handles dispatch.',steps:[['Capture the essentials','Ask for the service need, job location, callback details, and the facts your dispatcher needs. Check your approved service area before promising a next step.'],['Define urgency','Agree on the situations that need immediate human attention. The agent follows approved escalation language; it does not diagnose a technical problem or promise an arrival time.'],['Prepare the handoff','Send useful context to the responsible person or connected system. Booking and dispatch integrations are confirmed during discovery.']],example:'A caller reports a water-heater leak. The workflow captures the address, contact details, and reported issue, then follows your approved urgency rules to route the request.',primary:'ai-front-desk',secondary:'workflow-automation',faq:['Can it quote a repair?','Only approved pricing information can be used. Work requiring inspection or diagnosis should be handed to your team.']},
 {slug:'industries/professional-services',name:'Professional services',title:'AI for Bay Area Professional Service Firms',headline:'More focus on clients.\nLess administrative drag.',description:'AI training, inquiry routing, and administrative workflows for Bay Area agencies, consultancies, law firms, and professional teams.',need:'Professional teams need useful context before a conversation starts. Organize new-client inquiries, draft routine communications, and make internal handoffs easier to follow.',steps:[['Organize inquiries','Collect the type of service requested, company context, and contact details. Route the inquiry to the appropriate team for review.'],['Prepare better drafts','Train staff to provide approved context, check factual statements, and edit tone before sending a client communication.'],['Coordinate next steps','Create internal tasks or reminders from an agreed trigger. Keep professional advice, conflict checks, and commitments with qualified staff.']],example:'A prospective client describes the help they need. The workflow prepares a structured intake summary and a task for the right person to review before responding.',primary:'workflow-automation',secondary:'ai-training',faq:['Can AI make professional decisions for us?','The scope focuses on administrative work and drafts. Your qualified staff retain professional judgment and review.']},
 {slug:'industries/tax-accounting',name:'Tax & accounting',title:'AI Workflows for Bay Area Tax and Accounting Firms',headline:'A more organized office.\nA clearer client handoff.',description:'Administrative AI workflows and team training for Bay Area CPAs, tax offices, and bookkeeping firms.',need:'Document requests, intake checklists, appointment inquiries, and status follow-ups can consume an accounting team’s attention. Start with a defined administrative process and the systems your firm approves.',steps:[['Clarify the checklist','Agree on required intake fields and document-request steps. Keep the client’s actual financial documents in the systems your firm has approved.'],['Prepare follow-ups','Use status changes to prepare reminders or staff tasks. Review recipients, context, and exceptions before client communications go out.'],['Train the team','Practice drafting administrative messages and reviewing AI output. Tax positions, accounting judgments, and final advice remain with qualified professionals.']],example:'A new-client intake creates an internal checklist and flags missing administrative information. Staff review the record and decide which document request to send.',primary:'workflow-automation',secondary:'ai-training',faq:['Should we put client financial records into the website demo?','No. The public demo works from public website information. Any client-data workflow needs a separate review of access, tools, and handling requirements.']},
 {slug:'industries/property-management',name:'Property & facilities',title:'AI for Bay Area Property and Facilities Teams',headline:'Every request.\nA clearer path to resolution.',description:'Maintenance intake, request routing, and workflow automation for Bay Area property managers and facilities teams.',need:'A maintenance request is more useful when the team knows the property, issue, contact details, and agreed urgency. Build intake around the information required to act.',steps:[['Collect the right context','Identify the property or unit, the reported issue, and a contact route. Define the required fields for a complete request.'],['Route by responsibility','Use the property, issue category, and approved urgency rules to prepare the appropriate team handoff.'],['Keep people in charge','Make emergency guidance and escalation explicit. The workflow organizes reported information; staff determine the response and service arrangements.']],example:'A tenant reports a heating problem. Intake captures the unit and callback details, prepares a maintenance request, and routes it according to the property team’s rules.',primary:'workflow-automation',secondary:'ai-front-desk',faq:['Can this connect to our property software?','We assess the product, API access, subscription tier, and required workflow before confirming an integration.']},
 {slug:'industries/retail-hospitality',name:'Retail & hospitality',title:'AI for Bay Area Retail and Hospitality Businesses',headline:'A thoughtful answer.\nA smoother day.',description:'AI front desks, staff training, and connected workflows for Bay Area shops, restaurants, and hospitality businesses.',need:'Help customers find approved information about hours, locations, and services while your team focuses on the people in front of them. Begin with the questions you hear every day.',steps:[['Answer routine questions','Prepare approved business information and define when a caller should speak with staff. Keep changing hours and services in the update process.'],['Organize requests','Capture inquiries about events, services, or special arrangements and route them for a staff response.'],['Connect selectively','Review feasibility before promising ordering, inventory, or reservation connections. Start with a request handoff when a direct connection is not available.']],example:'A customer asks about a private event. The agent uses approved information, captures the date and contact details, and prepares a callback request for the team.',primary:'ai-front-desk',secondary:'ai-training',faq:['Can it confirm a reservation or inventory?','Only when a suitable live system connection and business rules have been agreed and tested. Otherwise it can collect a request for staff review.']},
 {slug:'industries/medical-dental',name:'Medical & dental',title:'Administrative AI for Bay Area Medical and Dental Offices',headline:'Support the front office.\nKeep care with your team.',description:'Explore administrative intake, callback requests, and AI training for Bay Area medical and dental offices.',need:'Start with non-clinical administrative tasks such as office information and callback requests. Any workflow involving patient information requires a separate assessment of approved systems, access, and handling requirements before implementation.',steps:[['Define the administrative scope','Choose the office information and request types the workflow can handle. Avoid collecting clinical details in an unapproved channel.'],['Prepare a staff handoff','Route callback or appointment inquiries to your office. A request is not a confirmed appointment unless an approved scheduling connection supports it.'],['Keep exceptions explicit','Use office-approved escalation language. Clinical advice, urgent medical concerns, and patient-care decisions stay with appropriate professionals.']],example:'A prospective patient asks how to contact the office about an appointment. The flow provides approved office information and, where an approved intake channel exists, routes a callback request.',primary:'ai-front-desk',secondary:'ai-training',faq:['Is patient-data handling included by default?','No. Systems, contracts, access controls, and patient-data handling requirements must be assessed separately before a patient-information workflow is implemented.']}
];
