import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {services, industries} from '../content/services.mjs';
import {guides as preparedGuides} from '../content/guides.mjs';
import {loadGenerated} from './editorial.mjs';
const guides=[...preparedGuides,...loadGenerated().map(g=>({...g,sectionSources:g.sections.map(s=>s.sourceIndexes),sections:g.sections.map(s=>[s.heading,s.body])}))];

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const today=process.env.BUILD_DATE || new Date().toISOString().slice(0,10);
if(!/^\d{4}-\d{2}-\d{2}$/.test(today)||Number.isNaN(Date.parse(today))) throw Error('Invalid BUILD_DATE');
const origin='https://dreamprotocol.ai';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const write=(f,s)=>{fs.mkdirSync(path.dirname(path.join(root,f)),{recursive:true});fs.writeFileSync(path.join(root,f),s);};
const hash=f=>createHash('sha256').update(read(f)).digest('hex').slice(0,10);
const version=hash('assets/site.css');
const uiVersion=hash('assets/site.js');
const pages=[];
const published=guides.filter(g=>g.status==='scheduled'&&g.publishOn<=today).sort((a,b)=>b.publishOn.localeCompare(a.publishOn)||a.slug.localeCompare(b.slug));
for(const g of guides){
 if(!/^[a-z0-9-]+$/.test(g.slug)||!/^\d{4}-\d{2}-\d{2}$/.test(g.publishOn))throw Error('Invalid guide path/date');
 if(g.status==='scheduled'&&(!g.description||g.sections.length<3||!services.some(s=>s.slug===g.service)))throw Error('Incomplete scheduled guide: '+g.slug);
}
const href=slug=>{const [pathname,query]=slug.split('?');return '/'+(pathname?pathname+'/':'')+(query?'?'+query:'');};
const link=(slug,label,cls='')=>`<a${cls?` class="${cls}"`:''} href="${href(slug)}">${esc(label)}</a>`;
const button=(slug,label='Let’s talk',secondary=false)=>link(slug,label+' ↗','button'+(secondary?' secondary':''));
const eyebrow=s=>`<p class="eyebrow">${esc(s)}</p>`;
const heading=(k,h,p='')=>`<div class="section-heading">${eyebrow(k)}<h2>${h}</h2>${p?`<p>${esc(p)}</p>`:''}</div>`;
const org={'@type':'Organization','@id':origin+'/#organization',name:'Dream Protocol',url:origin+'/',email:'hello@dreamprotocol.ai',logo:origin+'/favicon.svg',founder:{'@type':'Person',name:'Dustin Poole'},areaServed:{'@type':'Place',name:'San Francisco Bay Area'}};
function nav(active=''){
 return `<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="shell nav-wrap"><a class="brand" href="/" aria-label="Dream Protocol home"><span class="brand-mark" aria-hidden="true"></span><span>dream<span class="brand-light">protocol</span><small>BUSINESS, EVOLVED.</small></span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="primary-nav"><span class="sr-only">Open menu</span><span></span><span></span></button><nav id="primary-nav" aria-label="Primary navigation">${[['services','Services'],['industries','Industries'],['bay-area-ai-services','Bay Area'],['resources','Resources'],['pricing','Pricing'],['about','About']].map(([s,l])=>`<a href="/${s}/"${active===s?' aria-current="page"':''}>${l}</a>`).join('')}</nav><div class="nav-status" aria-hidden="true"><i></i><span>AI ONLINE</span></div>${button('contact','Automate something')}</div></header>`;
}
function footer(){return `<footer><div class="footer-glow" aria-hidden="true"></div><div class="shell"><div class="footer-command"><span><i></i>DREAMPROTOCOL SYSTEM</span><b>BUSINESS, EVOLVED.</b><span>AI / VOICE / AUTOMATION / INTEGRATION</span></div><div class="footer-top"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"></span>dream<span class="brand-light">protocol</span></a><p>Your business.<br><em>Running smarter.</em></p><a class="email-link" href="mailto:hello@dreamprotocol.ai">hello@dreamprotocol.ai ↗</a></div><div class="footer-columns"><div><h2>What we do</h2>${services.map(s=>link(s.slug,s.name)).join('')}</div><div><h2>Your business</h2>${industries.map(s=>link(s.slug,s.name)).join('')}</div><div><h2>Explore</h2>${[['bay-area-ai-services','Serving the Bay Area'],['pricing','Scope & pricing'],['resources','Guides & insights'],['about','About Dream Protocol'],['contact','Start automating']].map(([s,l])=>link(s,l)).join('')}</div><div><h2>System status</h2><p class="footer-live"><i></i> Ready to build</p><p>San Francisco Bay Area<br>Remote + onsite projects</p></div></div><div class="footer-bottom"><span>© ${today.slice(0,4)} Dream Protocol</span><span>YOUR BUSINESS → DREAM PROTOCOL → DONE</span><a href="/resources/feed.xml">RSS feed ↗</a></div></div></footer>`;}
function cta(){return `<section class="cta-band"><div class="cta-grid" aria-hidden="true"></div><div class="shell"><div>${eyebrow('READY WHEN YOU ARE')}<h2>Show us the bottleneck.<br><em>We’ll build the system.</em></h2><p>One annoying process is enough to start. Calls, follow-up, intake, handoffs, data entry, scheduling — bring the friction.</p></div><div class="cta-actions">${button('contact','Show us what to automate')}<a class="text-link" href="/#demo">Try the live AI demo ↗</a></div></div></section>`;}
const protocolBar=()=>`<div class="protocol-bar" aria-hidden="true"><div class="shell"><span>AI BUSINESS AUTOMATION</span><span class="protocol-live"><i></i>SYSTEM ONLINE</span><span>VOICE · WORKFLOWS · INTEGRATIONS · CUSTOM AI</span></div></div>`;
function layout(slug,title,description,body,{active='',schema=[],crumbs=[],home=false,article=false,noindex=false}={}){
 const url=origin+href(slug);
 const breadcrumb=crumbs.length?[{'@type':'BreadcrumbList',itemListElement:[{name:'Home',item:origin+'/'},...crumbs.map(([s,n])=>({name:n,item:origin+href(s)}))].map((x,i)=>({'@type':'ListItem',position:i+1,...x}))}]:[];
 const graph=[org,{'@type':'WebSite','@id':origin+'/#website',name:'Dream Protocol',url:origin+'/'},{'@type':'WebPage','@id':url+'#webpage',url,name:title,description,isPartOf:{'@id':origin+'/#website'},about:{'@id':origin+'/#organization'}},...breadcrumb,...schema];
 const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Dream Protocol</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}">${noindex?'<meta name="robots" content="noindex">':''}<meta name="theme-color" content="#101717"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${esc(title)} | Dream Protocol"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/public/dream-protocol-abstract.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="Dream Protocol guides" href="/resources/feed.xml"><link rel="stylesheet" href="/assets/site.css?v=${version}"><script defer src="/attribution.js"></script><script defer src="/assets/site.js?v=${uiVersion}"></script>${home?`<script>window.DREAMPROTOCOL_CONFIG={businessAnalysisEndpoint:"https://api.dreamprotocol.ai/analyze-business",vapiPublicKey:"ec40770e-0ff1-482c-929e-5288315e24b1",vapiAssistantId:"30ccf544-cd70-4ba6-8b23-fcd9ff5a4fec"};</script><script defer src="/app.35e2b7721f.js"></script>`:''}<script type="application/ld+json">${json({'@context':'https://schema.org','@graph':graph})}</script></head>
<body data-page="${esc(slug||'home')}"${home?' data-home="true"':''}>${nav(active)}${home?'':protocolBar()}<main id="main">${body}</main>${footer()}</body></html>\n`;
 if(!noindex)pages.push({slug,url});
 write(slug?slug+'/index.html':'index.html',html);
}
const crumbs=(items)=>`<div class="shell breadcrumbs"><a href="/">Home</a>${items.map(([s,n],i)=>`<span aria-hidden="true">/</span>${i===items.length-1?`<span>${esc(n)}</span>`:link(s,n)}`).join('')}</div>`;
const serviceCard=(s,i)=>`<a href="/${s.slug}/" class="service-card"><div class="card-top"><span class="service-icon" aria-hidden="true">${s.icon}</span><span class="card-number">0${i+1}</span></div><p class="eyebrow">${esc(s.tag)}</p><h3>${esc(s.name)} <span aria-hidden="true">↗</span></h3><p>${esc(s.description)}</p><div class="card-price">${esc(s.price)} <span>${esc(s.unit)}</span></div></a>`;
const industryCards=()=>`<div class="industry-grid">${industries.map((s,i)=>`<a href="/${s.slug}/" class="industry-card"><span>0${i+1}</span><h3>${esc(s.name)}</h3><span aria-hidden="true">↗</span></a>`).join('')}</div>`;
const guideCard=g=>`<a class="guide-card" href="/resources/${g.slug}/"><div class="guide-art art-${g.service}" aria-hidden="true"><span>${services.find(s=>s.slug===g.service)?.icon||'↗'}</span></div><div class="guide-copy"><p class="eyebrow">${esc(g.category)} <span> / GUIDE</span></p><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p><span class="text-link">Read the guide ↗</span></div></a>`;
const faq=items=>`<section class="shell section faq-section">${heading('A little more clarity','Questions, answered.')}<div>${items.map(([q,a])=>`<details><summary>${esc(q)}<span aria-hidden="true">+</span></summary><p>${esc(a)}</p></details>`).join('')}</div></section>`;
const processSection=()=>`<section id="implementation" class="section shell">${heading('HOW IT GOES LIVE','From friction.<br>To finished.','A direct path from the thing wasting your time to a system doing the work.')}<div class="process-grid">${[['01','Find the drag','Map the repeated work, handoffs, systems, and places your team loses time.'],['02','Design the system','Define the AI, integrations, guardrails, escalation points, and the outcome it must deliver.'],['03','Make it real','Build it, connect it, test real scenarios, and tune it against the way your business actually operates.'],['04','Keep it sharp','Measure what works, improve the weak spots, and expand only where the automation earns its keep.']].map(([n,t,p])=>`<article><span>${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>`;
const regional=()=>`<section class="regional section"><div class="shell regional-grid"><div>${eyebrow('Built for the Bay Area')}<h2>Big possibilities.<br><em>Local understanding.</em></h2><p>From a neighborhood shop to a growing operations team. We help businesses across the San Francisco Bay Area turn AI into useful, everyday work.</p>${button('bay-area-ai-services','Explore Bay Area services',true)}</div><div class="region-visual"><span class="region-stamp">37.7749° N &nbsp; 122.4194° W</span><div class="region-orbit" aria-hidden="true"><i></i><i></i><i></i><b>DP</b></div><div class="region-names"><span>San Francisco</span><span>Peninsula</span><span>South Bay</span><span>East Bay</span><span>North Bay</span></div><small>Serving all nine Bay Area counties</small></div></div></section>`;

// Homepage: one narrative. Detail pages carry depth; the overview moves visitors forward.
layout('','AI Business Automation for Bay Area Businesses','AI business automation that answers calls, captures leads, books appointments, connects systems, and handles repetitive work for Bay Area businesses.',`
<section class="home-hero dp-wow" id="top"><div class="hero-aurora" aria-hidden="true"></div><div class="shell hero-grid"><div class="hero-copy">${eyebrow('AI BUSINESS AUTOMATION / LIVE')}<h1>Put your business<br><em>on autopilot.</em></h1><p class="hero-intro">Calls answered. Leads captured. Appointments booked.<br>Follow-ups sent. Systems updated. Automatically.</p><p class="hero-sub">Dream Protocol builds AI that works inside the business you already run — not another dashboard your team has to babysit.</p><div class="hero-actions"><a class="button hero-primary" href="#demo">Build my AI demo <span>↗</span></a><a class="text-link hero-secondary" href="/contact/">Show me what to automate <span>↗</span></a></div><div class="hero-footnote"><span class="status-dot"></span> LIVE AI · VOICE · WORKFLOWS · INTEGRATIONS</div></div><div class="automation-core" aria-label="Illustration of an AI automation workflow"><div class="core-head"><span><i class="status-dot"></i>DREAMPROTOCOL CORE</span><b>LIVE</b></div><div class="core-stage" aria-hidden="true"><i class="core-ring ring-one"></i><i class="core-ring ring-two"></i><i class="core-ring ring-three"></i><div class="core-mark"><span>DP</span><small>AI CORE</small></div></div><div class="event-feed"><div class="event-row"><span>01</span><b>INCOMING CALL</b><em>AI answers</em></div><div class="event-row"><span>02</span><b>NEW LEAD</b><em>Qualified</em></div><div class="event-row"><span>03</span><b>CALENDAR</b><em>Appointment booked</em></div><div class="event-row"><span>04</span><b>CRM</b><em>Customer updated</em></div><div class="event-row"><span>05</span><b>FOLLOW-UP</b><em>Message sent</em></div></div><div class="core-foot"><span>YOUR BUSINESS</span><b>→</b><span>DREAM PROTOCOL</span><b>→</b><span>DONE</span></div></div></div><a class="demo-float-cta" href="#demo">TRY IT ON YOUR BUSINESS <span>↗</span></a></section>
<div class="principles-strip dp-outcome-strip"><div class="shell"><span>ANSWER CALLS</span><span>BOOK APPOINTMENTS</span><span>QUALIFY LEADS</span><span>FOLLOW UP 24/7 ↗</span></div></div>
<section class="demo-section section dp-demo-priority" id="demo"><div class="shell demo-grid"><div>${eyebrow('01 / BUILD YOUR DEMO')}<h2>Don’t imagine it.<br><em>Try it on your business.</em></h2><p>Drop in your website. Dream Protocol learns the public details and builds a first-pass AI front desk around your business.</p><p class="small-copy">Then start a live voice conversation. This is not a video or a canned chatbot — it is your business turned into an AI demo.</p>${link('ai-front-desk','See what else we can automate ↗','text-link')}</div><div class="demo-window"><div class="window-bar"><span><i></i><i></i><i></i></span><small>DREAM PROTOCOL / LIVE DEMO</small><span>↗</span></div>${read('content/partials/demo.html')}<div class="demo-bottom">Front desk from $399/month <span>Setup from $995</span></div></div></div></section>
<section class="section shell" id="services"><div class="section-heading split"><div>${eyebrow('02 / AI THAT DOES THE WORK')}<h2>Your busywork.<br><em>Handled.</em></h2></div><p>Start with the pain you feel today: missed calls, manual follow-up, disconnected systems, repetitive admin. We build the AI around that.</p></div><div class="service-grid">${services.map(serviceCard).join('')}</div></section>
<section class="section shell" id="industries">${heading('03 / Your business, your way','Different businesses.<br><em>Shared possibilities.</em>','The starting point is your work. Explore how a clearer intake, better handoff, or more confident team could fit your business.')}<div class="industry-examples">${read('content/partials/industries.html')}</div>${industryCards()}<p class="section-note">Don’t see your industry? ${link('contact','Bring us your workflow.')} Every kind of Bay Area business is welcome.</p></section>
${processSection()}${regional()}
<section class="section shell recording-grid" id="recording"><div>${eyebrow('A conversation, brought to life')}<h2>Hear the<br><em>possibility.</em></h2><p>An illustrative medical front-desk conversation. A recorded example, played when you choose.</p></div><div class="audio-card"><span class="eyebrow">FRONT DESK / RECORDED EXAMPLE</span><div class="audio-wave" aria-hidden="true">${Array.from({length:34},(_,i)=>`<i style="--h:${18+(i*37)%66}px"></i>`).join('')}</div><audio controls preload="none" aria-label="Recorded medical front-desk example"><source src="/demo-audio/dreamprotocol-medical-demo.mp3" type="audio/mpeg"></audio></div></section>
<section class="section resources-section"><div class="shell"><div class="section-heading split"><div>${eyebrow('Practical thinking')}<h2>A little clarity.<br><em>A smarter next step.</em></h2></div>${link('resources','Explore the resource library ↗','text-link')}</div><div class="guide-grid">${published.slice(0,3).map(guideCard).join('')}</div></div></section>
<section class="section shell price-preview" id="pricing"><div>${eyebrow('A clear place to start')}<h2>Scope first.<br><em>No guesswork.</em></h2></div><div><p>Start with a $750 team workshop, a focused automation from $1,500, or an AI front desk from $399/month with setup from $995. We agree on what’s included before work begins.</p>${button('pricing','Explore scope & pricing',true)}</div></section>
<section class="contact-section section" id="contact"><div class="shell contact-grid"><div>${eyebrow('Let’s make your next move')}<h2>What would you<br><em>automate first?</em></h2><p>Show us one annoying process in your business. We’ll show you how AI can take it off your plate.</p><a href="mailto:hello@dreamprotocol.ai" class="text-link">hello@dreamprotocol.ai ↗</a></div>${read('content/partials/contact.html')}</div></section>`,{home:true});

layout('services','AI Services for Bay Area Businesses','Explore AI training, receptionists, workflow automation, integration, managed support, and custom projects for your Bay Area business.',`${crumbs([['services','Services']])}<section class="page-hero shell">${eyebrow('ONE CONNECTED APPROACH')}<h1>AI that actually<br><em>does the work.</em></h1><p>Answer calls. Move data. Follow up. Train teams. Connect systems. Start with one painful workflow and make it disappear.</p></section><section class="shell section compact"><div class="service-grid">${services.map(serviceCard).join('')}</div></section>${processSection()}${cta()}`,{active:'services',crumbs:[['services','Services']]});

for(const s of services){
 const guide=published.find(g=>g.service===s.slug)||published.find(g=>g.slug===s.guide);
 layout(s.slug,s.title,s.description,`${crumbs([['services','Services'],[s.slug,s.name]])}<section class="page-hero shell detail-hero"><div>${eyebrow(s.name+' / BAY AREA')}<h1>${esc(s.headline).replace('\n','<br>')}</h1><p>${esc(s.description)}</p><div class="actions">${button('contact','Automate this workflow')}${s.slug==='ai-front-desk'?'<a class="text-link" href="/#demo">Try the live demo ↗</a>':link('pricing','View scope & pricing ↗','text-link')}</div></div><div class="detail-art"><img src="/public/${s.image}" alt="" width="1536" height="1024"><span>${esc(s.tag)} / Dream Protocol</span></div></section><section class="section shell detail-intro"><div>${eyebrow('A practical starting point')}<h2>${esc(s.name)}.<br><em>Built around your work.</em></h2></div><p>${esc(s.intro)}</p></section><section class="section pale-section"><div class="shell"><div class="three-grid">${s.points.map(([h,p],i)=>`<article class="feature"><span class="step-number">0${i+1}</span><h2>${esc(h)}</h2><p>${esc(p)}</p></article>`).join('')}</div></div></section><section class="section shell example-grid"><div class="example-panel">${eyebrow('An illustrative workflow')}<h2>${esc(s.example[0])}</h2><p>${esc(s.example[1])}</p><div class="mini-flow"><span>Context</span><b>→</b><span>Clear rules</span><b>→</b><span>Next step</span></div><small>Example only. The final workflow is agreed with your team.</small></div><div class="scope-panel">${eyebrow('What’s included')}<h2>${esc(s.price)} <small>${esc(s.unit)}</small></h2><p>${esc(s.setup)}</p><ul class="check-list">${s.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="small-copy">Software licenses, third-party usage, custom APIs, data cleanup, and additional scope are quoted separately where needed.</p>${button('contact','Build my starting point')}</div></section>${faq(s.faqs)}<section class="section shell related-section">${heading('The next useful connection','Build on your next step.')}<div class="related-grid">${s.related.map(x=>services.find(v=>v.slug===x)).map(serviceCard).join('')}${guide?guideCard(guide):`<a class="related-note" href="/industries/"><span class="eyebrow">YOUR BUSINESS</span><h3>See how it fits your industry.</h3><p>Explore the intake, training, and workflow ideas relevant to your team.</p><span>Explore industries ↗</span></a>`}</div></section>${cta()}`,{active:'services',crumbs:[['services','Services'],[s.slug,s.name]],schema:[{'@type':'Service',name:s.name,description:s.description,url:origin+href(s.slug),provider:{'@id':origin+'/#organization'},areaServed:org.areaServed}]});
}

layout('industries','AI for Every Kind of Bay Area Business','Explore practical AI workflows for Bay Area service teams, professional firms, accounting offices, retailers, property teams, and more.',`${crumbs([['industries','Industries']])}<section class="page-hero shell">${eyebrow('YOUR BUSINESS, YOUR WORKFLOW')}<h1>Your business has a rhythm.<br><em>AI should learn it.</em></h1><p>We build around your calls, customers, handoffs, tools, rules, and exceptions — not around a generic AI template.</p></section><section class="section shell compact">${industryCards()}<div class="wide-note"><h2>Your industry isn’t the limit.</h2><p>Startups, nonprofits, education teams, and other businesses are welcome. Bring a repeated task, a training need, or an idea.</p>${button('contact','Tell us about your business',true)}</div></section>${regional()}${cta()}`,{active:'industries',crumbs:[['industries','Industries']]});
for(const s of industries){layout(s.slug,s.title,s.description,`${crumbs([['industries','Industries'],[s.slug,s.name]])}<section class="page-hero shell">${eyebrow(s.name+' / BAY AREA')}<h1>${esc(s.headline).replace('\n','<br>')}</h1><p>${esc(s.need)}</p><div class="actions">${button('contact','Show us your workflow')}${link(s.primary,'Explore '+services.find(x=>x.slug===s.primary).name.toLowerCase()+' ↗','text-link')}</div></section><section class="section pale-section"><div class="shell">${heading('Where to begin','Make the next step clearer.')}<div class="three-grid">${s.steps.map(([t,p],i)=>`<article class="feature"><span class="step-number">0${i+1}</span><h3>${esc(t)}</h3><p>${esc(p)}</p></article>`).join('')}</div></div></section><section class="section shell"><div class="wide-note">${eyebrow('ILLUSTRATIVE EXAMPLE')}<h2>What it could look like.</h2><p>${esc(s.example)}</p><small>Example only. Your systems, requirements, and approved process shape the implementation.</small></div></section>${faq([s.faq,['Do you serve our part of the Bay Area?','We serve businesses across San Francisco, San Mateo, Santa Clara, Alameda, Contra Costa, Marin, Sonoma, Napa, and Solano counties. Start remotely; onsite delivery is quoted separately.']])}<section class="section shell">${heading('The services behind the workflow','Build my starting point.')}<div class="two-grid">${[s.primary,s.secondary].map(x=>services.find(v=>v.slug===x)).map(serviceCard).join('')}</div></section>${cta()}`,{active:'industries',crumbs:[['industries','Industries'],[s.slug,s.name]]});}

layout('bay-area-ai-services','AI Consulting & Services Across the San Francisco Bay Area','AI training, automation, integrations, and front desks serving all nine Bay Area counties. Explore services for your business and start a conversation.',`${crumbs([['bay-area-ai-services','Bay Area']])}<section class="page-hero shell">${eyebrow('ALL NINE COUNTIES. EVERY KIND OF BUSINESS.')}<h1>Bay Area speed.<br><em>AI that keeps up.</em></h1><p>AI systems for the businesses that keep the Bay Area moving. Faster response, cleaner handoffs, connected tools, and less repetitive work.</p><div class="actions">${button('contact','Talk about your business')}${link('services','Explore our services ↗','text-link')}</div></section>${regional()}<section class="section shell">${heading('Across the region','One connected Bay Area.','Start with a remote conversation. Onsite workshops and project work are quoted for your location and scope.')}<div class="region-grid">${[['San Francisco','San Francisco County','Customer inquiries, team training, and connected back-office work for businesses throughout the city.'],['The Peninsula','San Mateo County','Practical workflows for office teams, independent firms, and local service businesses.'],['South Bay','Santa Clara County','Training and integration projects for growing teams, shops, and service operations.'],['East Bay','Alameda & Contra Costa counties','Clearer intake and handoffs for teams working across communities and service areas.'],['North Bay','Marin, Sonoma, Napa & Solano counties','Business information, inquiry routing, and practical automation for local teams.']].map(([n,c,p])=>`<article class="region-card">${eyebrow(c)}<h3>${n}</h3><p>${p}</p></article>`).join('')}</div><p class="section-note">These are service areas. Project delivery and onsite availability are agreed during scoping.</p></section><section class="section pale-section"><div class="shell">${heading('Your business belongs here','A practical fit.<br>Across industries.')} ${industryCards()}</div></section>${faq([['Do you work with businesses outside technology?','Yes. We work across industries, including local shops, professional offices, contractors, hospitality, and property teams. The task and requirements determine the project.'],['Do we need to replace our software?','We start by reviewing the systems you already use. Integration depends on the APIs, permissions, and licenses available. We discuss any required changes before agreeing on scope.'],['Can our first step be a workshop?','Yes. The starting workshop is a two-hour remote session for up to five people at $750, with a prompt guide and one 30-minute follow-up. Onsite delivery and larger groups are quoted separately.']])}${cta()}`,{active:'bay-area-ai-services',crumbs:[['bay-area-ai-services','Bay Area']]});

layout('pricing','AI Services: Scope & Pricing','Explore Dream Protocol’s starting prices for AI training, front desks, workflow automation, integrations, managed support, and custom projects.',`${crumbs([['pricing','Pricing']])}<section class="page-hero shell">${eyebrow('CLEAR SCOPE. PRACTICAL STARTING POINTS.')}<h1>Start small.<br><em>Make it real.</em></h1><p>Clear starting prices. Defined scope. No mystery consulting cloud. Pick the pain point and see what it takes to automate it.</p></section><section class="section shell compact"><div class="pricing-grid">${services.map(s=>`<article class="price-card">${eyebrow(s.tag)}<h2>${esc(s.name)}</h2><div class="price">${esc(s.price)}<small>${esc(s.unit)}</small></div><p>${esc(s.setup)}</p><ul class="check-list">${s.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${button('contact?service='+encodeURIComponent(s.name),'Discuss this service')}${link(s.slug,'Explore the service ↗','text-link')}</article>`).join('')}</div><p class="pricing-terms">Starting prices cover a defined scope. Software licenses, third-party usage, larger teams, custom APIs, data cleanup, and additional locations are quoted separately. Managed support is separate from front-desk service.</p></section>${faq([['What happens before we commit?','We discuss your goals, current tools, and requirements, then agree on a defined scope. Custom projects receive a proposal with milestones and deliverables.'],['Can we combine services?','Yes. Training, integration, and workflow projects can support the same outcome. The proposal explains each part and its price.'],['Are there setup or usage charges for the AI front desk?','Yes. Setup starts at $995 for one business/location. The usage allowance and any overage terms are quoted upfront.']])}${cta()}`,{crumbs:[['pricing','Pricing']]});

layout('about','About Dream Protocol','Meet Dream Protocol: practical AI training, integration, and automation for Bay Area businesses, founded by Dustin Poole.',`${crumbs([['about','About']])}<section class="page-hero shell">${eyebrow('PRACTICAL EXPERIENCE. FORWARD THINKING.')}<h1>AI without<br><em>the theater.</em></h1><p>Dream Protocol is built around one idea: technology should remove work, connect work, or make people better at it. If it does none of those things, it is noise.</p></section><section class="section shell founder-grid"><div class="founder-photo"><img src="/public/logos/customers/dustin-poole-about.png" width="1200" height="1200" alt="Dustin Poole, founder of Dream Protocol" loading="lazy"></div><div>${eyebrow('THE PERSON BEHIND DREAM PROTOCOL')}<h2>Dustin Poole</h2><p class="founder-title">Founder</p><p>Practical experience across business IT, infrastructure, cloud, voice, automation, and integration.</p><p>That combination shapes the work: understand the business process, check how the systems connect, and give the people using them a clear way forward.</p><p>Dream Protocol serves businesses across the San Francisco Bay Area. Projects begin with the task you want to improve and a scope you can evaluate.</p>${button('contact','Start automating',true)}</div></section>${processSection()}${cta()}`,{active:'about',crumbs:[['about','About']]});

layout('contact','Talk to Dream Protocol','Tell us about your Bay Area business and the work you want to improve. Discuss AI training, front desks, automation, or a custom project.',`${crumbs([['contact','Contact']])}<section class="page-hero shell"><div class="contact-grid"><div>${eyebrow('YOUR NEXT CHAPTER STARTS HERE')}<h1>Show us what<br><em>wastes your time.</em></h1><p>Give us the ugly workflow, the missed calls, the copy-paste process, or the system that never talks to the other system.</p><a class="email-link" href="mailto:hello@dreamprotocol.ai">hello@dreamprotocol.ai ↗</a><div class="contact-next"><h2>What happens next</h2><ol><li>You show us the friction.</li><li>We map the AI + systems path.</li><li>You get a clear scope before anything is built.</li></ol></div></div>${read('content/partials/contact.html')}</div></section>`,{crumbs:[['contact','Contact']]});

layout('resources','Practical AI Guides for Business','Guides to AI receptionists, team training, workflow automation, and systems integration. Practical reading for your next business decision.',`${crumbs([['resources','Resources']])}<section class="page-hero shell">${eyebrow('THE DREAM PROTOCOL RESOURCE LIBRARY')}<h1>Skip the AI hype.<br><em>Build what works.</em></h1><p>Straight answers for businesses deciding what to automate, what to connect, what AI can actually handle, and what should stay human.</p></section><section class="section shell compact"><div class="guide-grid">${published.map(guideCard).join('')}</div><div class="wide-note"><h2>Start with your question.</h2><p>Not sure which guide fits your situation? Tell us what you are trying to improve and we’ll help identify a practical starting point.</p>${button('contact','Ask about your workflow',true)}</div></section>${cta()}`,{active:'resources',crumbs:[['resources','Resources']]});
for(const g of published){
 const s=services.find(s=>s.slug===g.service);
 const slug='resources/'+g.slug;
 layout(slug,g.title,g.description,`${crumbs([['resources','Resources'],[slug,g.title]])}<article><header class="page-hero shell article-hero">${eyebrow(g.category+' / PRACTICAL GUIDE')}<h1>${esc(g.title)}</h1><p>${esc(g.description)}</p><div class="article-meta"><a href="/about/">Dream Protocol</a><span>Published <time datetime="${g.publishOn}">${g.publishOn}</time></span><span>${Math.max(3,Math.ceil(g.sections.map(x=>x.join(' ')).join(' ').split(/\s+/).length/200))} min read</span></div></header><div class="shell article-layout"><aside class="article-nav"><p class="eyebrow">IN THIS GUIDE</p>${g.sections.map(([h],i)=>`<a href="#section-${i+1}">${esc(h)}</a>`).join('')}${link(s.slug,'Explore '+s.name.toLowerCase()+' ↗','text-link')}</aside><div class="article-body"><div class="takeaway">${eyebrow('THE USEFUL TAKEAWAY')}<p>${esc(g.takeaway)}</p></div>${g.sections.map(([h,p],i)=>`<section id="section-${i+1}"><h2>${esc(h)}</h2><p>${esc(p)}</p>${g.sectionSources?.[i]?.length?`<p class="source-links">Sources: ${g.sectionSources[i].map(n=>`<a href="${esc(g.sources[n].url)}" rel="noopener noreferrer">${esc(g.sources[n].title)}</a>`).join(' · ')}</p>`:''}</section>`).join('')}<section class="article-checklist"><h2>Your next-step checklist</h2><ul class="check-list">${g.checklist.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><div class="article-source">${g.sources?`<p>Researched and checked with AI on <time datetime="${esc(g.generation.sourceCheckedOn)}">${esc(g.generation.sourceCheckedOn)}</time>. Source links appear beside the sections they support. Vendor features can change; confirm availability before implementation.</p>`:''}<p>About this guide: prepared for Dream Protocol’s resource library with AI assistance. It provides general planning guidance and uses Dream Protocol’s published service scope where pricing is discussed. It is not a client case study.</p>${link('pricing','Check current scope and pricing ↗')}</div></div></div></article><section class="section shell">${heading('Put the thinking to work','Explore your next step.')}<div class="two-grid">${serviceCard(s,0)}${published.find(x=>x.slug!==g.slug)?guideCard(published.find(x=>x.slug!==g.slug)):''}</div></section>${cta()}`,{active:'resources',article:true,crumbs:[['resources','Resources'],[slug,g.title]],schema:[{'@type':'Article',headline:g.title,description:g.description,datePublished:g.publishOn,dateModified:g.updatedOn||g.publishOn,author:{'@type':'Organization',name:'Dream Protocol',url:origin+'/about/'},publisher:{'@id':origin+'/#organization'},mainEntityOfPage:origin+href(slug),image:origin+'/public/dream-protocol-abstract.webp'}]});
}
// An old generated future page cannot leak into a date-controlled build.
for(const g of guides.filter(g=>!published.includes(g))){const f=path.join(root,'resources',g.slug,'index.html');if(fs.existsSync(f))fs.unlinkSync(f);}
layout('404','Page Not Found','Find your way back to Dream Protocol’s services and resources.',`<section class="page-hero shell">${eyebrow('404 / A DIFFERENT NEXT STEP')}<h1>Let’s get you<br><em>back on track.</em></h1><p>This page could not be found. Explore our services or tell us what you’re looking for.</p><div class="actions">${button('services','Explore services')}${button('contact','Talk to us',true)}</div></section>`,{noindex:true});
fs.renameSync(path.join(root,'404/index.html'),path.join(root,'404.html'));
const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${esc(p.url)}</loc></url>`).join('\n')}\n</urlset>\n`;
write('sitemap.xml',sitemap);write('public/sitemap.xml',sitemap);
const robots='User-agent: *\nAllow: /\nSitemap: https://dreamprotocol.ai/sitemap.xml\n';write('robots.txt',robots);write('public/robots.txt',robots);
write('resources/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Dream Protocol — Practical AI Guides</title><link>${origin}/resources/</link><description>Practical AI thinking for business.</description><language>en-us</language>${published.map(g=>`<item><title>${esc(g.title)}</title><link>${origin}/resources/${g.slug}/</link><guid isPermaLink="true">${origin}/resources/${g.slug}/</guid><pubDate>${new Date(g.publishOn+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(g.description)}</description></item>`).join('')}</channel></rss>`);
write('content/published.json',JSON.stringify(published.map(g=>({slug:g.slug,publishOn:g.publishOn})),null,2)+'\n');
write('.nojekyll','');
console.log(`Built ${pages.length} indexable pages; ${published.length} guides published; ${guides.length-published.length} queued. Date: ${today}`);
